apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: dzemanov-org
  annotations:
    github.com/project-slug: 'dzemanov-org/test'
spec:
  type: website
  lifecycle: production
  owner: user:dzemanov
  system: examples
